from io import BytesIO
from datetime import datetime

from pathlib import Path
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

OUTPUT_DIR = Path("outputs")
REPORT_DIR = OUTPUT_DIR / "reports"
TRANSCRIPT_DIR = OUTPUT_DIR / "transcripts"

REPORT_DIR.mkdir(parents=True, exist_ok=True)
TRANSCRIPT_DIR.mkdir(parents=True, exist_ok=True)

TITLE_COLOR = HexColor("#1F4E79")
SECTION_COLOR = HexColor("#0B6E4F")


def generate_pdf(report: str, meeting_type: str, model_name: str):
    """
    Generate a professional Meeting Report PDF.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.fontSize = 24
    title_style.leading = 30
    title_style.alignment = 1
    title_style.textColor = TITLE_COLOR

    subtitle_style = styles["Heading2"]
    subtitle_style.alignment = 1
    subtitle_style.spaceAfter = 20

    heading_style = styles["Heading2"]
    heading_style.fontSize = 16
    heading_style.leading = 22
    heading_style.spaceBefore = 12
    heading_style.spaceAfter = 8
    heading_style.textColor = SECTION_COLOR

    normal_style = styles["BodyText"]
    normal_style.fontSize = 11
    normal_style.leading = 18

    story = []

    # ---------- HEADER ----------

    story.append(
        Paragraph("🧠 MeetMind AI", title_style)
    )

    story.append(
        Paragraph(
            "Professional Meeting Report",
            subtitle_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    generated_time = datetime.now().strftime("%d %B %Y %I:%M %p")

    story.append(
        Paragraph(f"<b>Meeting Type:</b> {meeting_type}", normal_style)
    )

    story.append(
        Paragraph(f"<b>Generated On:</b> {generated_time}", normal_style)
    )

    story.append(
        Paragraph(f"<b>AI Model:</b> {model_name}", normal_style)
    )

    story.append(Spacer(1, 0.35 * inch))

    # ---------- REPORT ----------

    for line in report.split("\n"):

        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):
            heading = line.replace("#", "").strip()
            story.append(
                Paragraph(
                    f"<b>{heading}</b>",
                    heading_style
                )
            )

        elif line.startswith("-"):
            bullet = "• " + line[1:].strip()
            story.append(
                Paragraph(bullet, normal_style)
            )

        else:
            story.append(
                Paragraph(line, normal_style)
            )

        story.append(Spacer(1, 0.12 * inch))

    # ---------- FOOTER ----------

    story.append(Spacer(1, 0.35 * inch))

    story.append(
       Paragraph(
            "<font color='#666666'><b>Generated by MeetMind AI • Powered by Gemini 3.5 Flash</b></font>",
            styles["Italic"],
        )
    )

    doc.build(story)

    buffer.seek(0)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    pdf_path = REPORT_DIR / f"Meeting_Report_{timestamp}.pdf"
    
    with open(pdf_path, "wb") as file:
        file.write(buffer.getvalue())
    buffer.seek(0)
    return buffer



def generate_docx(report:str, meeting_type: str, model_name: str):
    """
    Generate a Professional DOCX meeting report.
    """
    document = Document()

    # ---------- TITLE ----------
    title = document.add_heading("🧠 MeetMind AI", level=0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = document.add_heading(
        "Professional Meeting Report",
        level=1
    )
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    # ---------- METADATA ----------
    generated_time = datetime.now().strftime("%d %B %Y %I:%M %p")

    meta = document.add_paragraph()
    meta.add_run("Meeting Type: ").bold = True
    meta.add_run(meeting_type)

    meta = document.add_paragraph()
    meta.add_run("Generated On: ").bold = True
    meta.add_run(generated_time)

    meta = document.add_paragraph()
    meta.add_run("AI Model: ").bold = True
    meta.add_run(model_name)

    document.add_paragraph("-" * 60)

    # ---------- CONTENT ----------
    for line in report.split("\n"):

        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):

            heading = line.replace("#", "").strip()
            document.add_heading(heading, level=2)

        elif line.startswith("-"):

            text = line[1:].strip()
            text = text.replace("**", "")

            document.add_paragraph(
                text,
                style="List Bullet"
            )

        else:

            clean = (
                line.replace("**", "")
                    .replace("*", "")
                    .replace("#", "")
            )

            paragraph = document.add_paragraph()
            run = paragraph.add_run(clean)
            run.font.size = Pt(11)

    document.add_paragraph("-" * 60)

    footer = document.add_paragraph()
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    run = footer.add_run(
        "Generated by MeetMind AI\nPowered by Gemini 3.5 Flash"
    )

    run.italic = True
    run.font.size = Pt(10)

    # ---------- SAVE ----------
    output = BytesIO()

    document.save(output)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    docx_path = REPORT_DIR / f"Meeting_Report_{timestamp}.docx"
    with open(docx_path, "wb") as file:
        file.write(output.getvalue())
    
    output.seek(0)

    return output